[local]
localhost ansible_connection=local

[redis_nodes]
redis-node-1 ansible_host=127.0.0.1 ansible_port=2221 redis_cluster_ip=10.10.0.11 redis_initial_role=master
redis-node-2 ansible_host=127.0.0.1 ansible_port=2222 redis_cluster_ip=10.10.0.12 redis_initial_role=master
redis-node-3 ansible_host=127.0.0.1 ansible_port=2223 redis_cluster_ip=10.10.0.13 redis_initial_role=master
redis-node-4 ansible_host=127.0.0.1 ansible_port=2224 redis_cluster_ip=10.10.0.14 redis_initial_role=replica redis_replica_of=redis-node-1
redis-node-5 ansible_host=127.0.0.1 ansible_port=2225 redis_cluster_ip=10.10.0.15 redis_initial_role=replica redis_replica_of=redis-node-2
redis-node-6 ansible_host=127.0.0.1 ansible_port=2226 redis_cluster_ip=10.10.0.16 redis_initial_role=replica redis_replica_of=redis-node-3


redis-node-7 ansible_host=127.0.0.1 ansible_port=2227 redis_cluster_ip=10.10.0.17 redis_initial_role=master
redis-node-8 ansible_host=127.0.0.1 ansible_port=2228 redis_cluster_ip=10.10.0.18 redis_initial_role=replica redis_replica_of=redis-node-7


[redis_masters_initial]
redis-node-1
redis-node-2
redis-node-3


redis-node-7


[redis_replicas_initial]        
redis-node-4
redis-node-5
redis-node-6


redis-node-8


[redis_nodes:vars]
ansible_user=ansible
ansible_ssh_private_key_file=infra/ssh/redis_cluster_key
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
